package com.atp.common;

/**
 * <p>Descript：</p>
 * Created by minglu on 2017/2/7.
 */
public class Constants {
    //================= 项目用到的所有常量数值请在此定义===================//
    public static final String INTERFACE_VERSION = "1.0";
    public static final String CHARSET = "UTF-8";
    public static final String CHARSET_GBK = "GBK";
    public static final String XML_HEAD = "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n";
    public static final String SCHEMAL_JSON = "json";
    public static final String REGOIN = "zh_cn";
    public static final String FILTER_CHARS = "~!@#$%^&*()-_+=?<>\':;\\/|";
    public static final String PROXY_ENABLED = "proxyEnabled";
    public static final String PROXY_HOST = "proxyHost";
    public static final String PROXY_PORT = "proxyPort";
    public static final String PROXY_ENABLED_VALUE = "1";
    public static final String ROOT_ELEMENT_NAME = "Message";
    public static final String ENCRY_PASS_KEY = "encry_pass_key";
    public static final String LH_INSTID = "YH0000001";
    public static final String FC_INSTID = "FC0000001";
    public static final String BLANK_S = "";
    public static final int AGE_18 = 18;
    public static final String VCODE = "654321";
    public static final String CARD_BIN_URL = "cardBinUrl";
    public static final String IMPORT_CARDAUTH_URL = "importCardAuthInfoUrl";
    public static final String CARD_BIN = "0000";
    public static final String CARD_TYPE = "1";
    public static final String WEB_SERVER_TYPE_H5 = "h5";
    public static final String MSG_TRADING_FAILURE_INFO = "交易失败：前台错误信息为：";
    public static final String TRADING_FAILURE_BACK_INFO = "交易失败：后台错误信息为：";
    public static final String PROJECT_NAME = "optt";
    public static final int VALIDATE_STATE = 1;
    public static final String INSTLD_LH = "instld_LH";
    public static final String INSTLD_FC = "instld_FC";
    public static final String PAY_TYPE = "1";
    public static final String STATUS_ZERO = "0";
    public static final String BUSINESS_CODE_SUBSCRIPTION = "20";
    public static final String BUSINESS_CODE_PURCHASE = "22";
    public static final String BUSINESS_CODE_REDEEM = "24";
    public static final String BUSINESS_CODE_REDEEM_0 = "0";
    public static final String BUSINESS_CODE_BONUS = "43";
    public static final String BUSINESS_CODE_OTHER_98 = "98";
    public static final String BUSINESS_CODE_01 = "01";
    public static final int ZERO = 0;
    public static final int ONE = 1;
    public static final int TWO = 2;
    public static final int THREE = 3;
    public static final int FOUR = 4;
    public static final int FIVE = 5;
    public static final int SIX = 6;
    public static final int SEVEN = 7;
    public static final int EIGHT = 8;
    public static final int NINE = 9;
    public static final int TEN = 10;
    public static final int ELEVEN = 11;
    public static final int TWELVE = 12;
    public static final int THIRTEN = 13;
    public static final int FOURTEN = 14;
    public static final int EIGHTEEN = 18;
    public static final int THIRTH = 30;
    public static final String INSTIDS_UNCHKBANK = "instids_unchkbank";
    public static final String INSTIDS_AFTERPAY = "instids_afterpay";
    public static final String MESS_TYPE_ACK_MESS_RG = "01";
    public static final String MESS_TYPE_ACK_MESS_SH = "02";
    public static final String MESS_TYPE_APP_MESS_SG = "03";
    public static final String MESS_TYPE_APP_MESS_SH = "04";
    public static final String MESS_TYPE_APP_MESS_SG_CHECK = "05";
    public static final String MESS_TYPE_APP_MESS_SH_CHECK = "06";
    public static final String MESS_TYPE_APP_MESS_UNION_SG_CHECK = "07";
    public static final String MESS_TYPE_APP_MESS_UNION_SH_CHECK = "08";
    public static final String MESS_TYPE_APP_MESS_UNION_SG = "09";
    public static final String MESS_TYPE_APP_MESS_UNION_SH_NOR = "10";
    public static final String MESS_TYPE_APP_MESS_UNION_SH_CUR = "11";
    public static final String MESS_TYPE_FIND_TRANS_PASS = "13";
    public static final long Five_Minutes = 300L;
    public static final int UTF_8 = 8;
    public static final int GBK = 15;
    public static final String SMS_SOURCE = "00";
    public static final String SMS_SOURCE_01 = "01";
    public static final String REDEEM_FLAG_0 = "0";
    public static final String REDEEM_FLAG_1 = "1";
    public static final String REDEEM_FLAG_2 = "2";
    public static final int startFastRedeemHour = 1;
    public static final int endFastRedeemHour = 20;
    public static final String FAST_REDEEM_INSIDS = "fastRedeem.instIds";
    public static final String FORMAT_TYPE = "###0.00";
    public static final int MAX_SINGLE_VALUE = 1000000;
    public static final String VAST_REDEEM_FLAG_0 = "0";
    public static final String VAST_REDEEM_FLAG_1 = "1";
    public static final String FUND_STS = "0,1,2,3,4,5,6,9,a";
    public static final String FUND_STS_0 = "0";
    public static final String FUND_STS_1 = "1";
    public static final String FUND_STS_2 = "2";
    public static final String FUND_STS_3 = "3";
    public static final String FUND_STS_4 = "4";
    public static final String FUND_STS_5 = "5";
    public static final String FUND_STS_6 = "6";
    public static final String FUND_STS_9 = "9";
    public static final String FUND_STS_a = "a";
    public static final int MAX_ERROR_TIMES = 5;
    public static final int SMS_CHECK_SUCCESS = 0;
    public static final int SMS_CHECK_FAILURE = 2;
    public static final String MSG_SUCCESS = "0000";
    public static final int TRADE_REPEATAPPLY = 2030;
    public static final String STATUS_02 = "02";
    public static final String STATUS_04 = "04";
    public static final String STATUS_06 = "06";
    public static final String BRANCH_CODE = "463";
    public static final String SPLIT_CHAR = ",";
    public static final String TREASURE_FUND = "000686";
    public static final String HOT_FUND = "hotFund";
    public static final String RATE_CALC_CHANNEL_ID = "0501";
    public static final String WEEK_YIELD_RATE = "周收益";
    public static final String MONTH_YIELD_RATE = "月收益";
    public static final String QUARTER_YIELD_RATE = "季收益";
    public static final String HALFYEAR_YIELD_RATE = "半年收益";
    public static final String YEAR_YIELD_RATE = "年收益";
    public static final String THIS_YEAR_YIELD_RATE = "今年以来收益";
    public static final String FUND_PROFIT_RATE = "成立以来";
    public static final String STATIC_VALUE = "--";
    public static final String BANK_INFO = "bankInfo";
    public static final String H5_PREFIX = "h5_";
    public static final String OPEN_API = "open.api";
    public static final String FORWARD = "forward:/";
    public static final String PARAM = "param";
    public static final String REQ_EMPTY = "";
    public static final String PRI_KEY = ".PRK";
    public static final String PUB_KEY = ".PUK";
    public static final String SIGN_FLAG = "1";
    public static final String VAST_REDEEM_FLAG = "1";
    public static final String NAN_FANG_TA = "nanFang_ta";
    public static final String NAN_FANG_FUNDCODE = "nanFang_fundCode";
    public static final String REDEEM_2_PURCHASE = "redeem2purchase";
    public static final int REDEEM_PURCHASE_FLAG = 0;
    public static final String FUND_TYPE = "7";
    public static final String G_USER_WAY = "0";

    public Constants() {
    }
}

